name: ootd
description: "Engineering project"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  riverpod_annotation: ^2.3.5
  supabase_flutter: ^2.5.3
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  flutter_form_builder: ^9.2.1
  easy_stepper: ^0.8.5+1
  step_progress_indicator: ^1.0.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  dio: ^5.6.0
  path_provider: ^2.1.4
  email_validator: ^3.0.0
  another_flushbar: ^1.12.30
  flutter_secure_storage: ^8.0.0
  json_annotation: ^4.8.1
  auto_route: ^8.1.4
  auto_route_generator: ^8.0.0
  linear_progress_bar: ^1.1.2
  flutter_staggered_animations: ^1.1.1
  flutter_tags: ^1.0.0-nullsafety.1
  carousel_slider: ^5.0.0
  flutter_expandable_fab: ^2.3.0
  screenshot: ^3.0.0
  simple_chips_input: ^1.2.0
  filter_list: ^1.0.3
  lottie: ^3.2.0
  smooth_sheets: ^0.10.2
  textfield_tags: ^3.0.1
  cached_network_image: ^3.4.0
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.1
  shared_preferences: ^2.5.3
  logger: ^2.5.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.3
  build_runner: ^2.4.6
  custom_lint: ^0.7.0
  flutter_lints: ^3.0.0

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#ffffff"
  image: assets/brand_logo.png
  android_12:
    image: assets/brand_logo.png
    color: "#ffffff"

flutter_launcher_icons:
  image_path_android: "assets/brand_logo.png"
  android: true

flutter:
  generate: true
  uses-material-design: true



  assets:
    - assets/season_icon/spring_cover.png
    - assets/season_icon/winter_cover.png
    - assets/season_icon/summer_cover.png
    - assets/season_icon/autumn_cover.png
    - .env
    - assets/brand_logo.png
    - assets/category_icon/category_icon_test.png
    - assets/tag_icon/work.png
    - assets/animations/check_success.json


